services:
  # A Docker web service
  - type: web
    name: orangeflow
    runtime: docker
    dockerfilePath: ./docker/render.Dockerfile
    branch: main
    plan: standard
    healthCheckPath: /health_check
    autoDeploy: false
    envVars:
      - key: LANGFLOW_DATABASE_URL
        value: sqlite:////app/data/.cache/orangeflow/orangeflow.db
      - key: LANGFLOW_HOST
        value: 0.0.0.0
      - key: LANGFLOW_PORT
        # default render port https://docs.render.com/web-services#port-binding
        value: 10000
      - key: LANGFLOW_LOG_LEVEL
        value: INFO
    disk:
      name: orangeflow-data
      mountPath: /app/data
